
<?php
/**
 * @file
 * This file contains all Drupal hooks for the module other than any
 * node hooks and block hooks. Those go in the [module name].chado_node.inc file
 * and [module_name].blocks.inc respectively
 *
 */

require ('theme/tripal_galaxy.theme.inc');

/**
 * Implementation of hook_init()
 */
function tripal_galaxy_init() {
  global $user;

  $library = libraries_detect('blend4php');
  if (user_access('administer galaxy', $user)) {
    if (!$library) {
      drupal_set_message(t('The blend4php library is not installed. The Galaxy module requires it.'), 'warning');
    }
  }
}



/**
 * Implements hook_libraries_info().
 *
 * For defining external libraries.
 */

function tripal_galaxy_libraries_info() {

  // A very simple library. No changing APIs (hence, no versions), no variants.
  // Expected to be extracted into 'sites/all/libraries/simple'.
  $libraries['blend4php'] = array(
    'name' => 'blend4php',
    'vendor url' => 'https://github.com/galaxyproject/blend4php',
    'download url' => 'https://github.com/galaxyproject/blend4php',
    'version arguments' => array(
      'file' => 'version.txt',
      'pattern' => '/^(.*)$/',
      'lines' => 1,
    ),
    'files' => array(
      'php' => array('galaxy.inc'),
    ),
  );

  return $libraries;
}


/**
 * Implementation of hook_permissions()
 *
 * Set the permission types that this module uses.
 *
 * @ingroup tripal_file
 */
function tripal_galaxy_permission() {
  return array (
    'use galaxy' => array (
      'title' => t ( 'Execute Published Galaxy Workflows' ),
      'description' => t ( 'Allows a user to submit a published workflow for execution on a remote Galaxy Instance' )
    ),
    'administer galaxy' => array (
      'title' => t ( 'Administer Galaxy' ),
      'description' => t ( 'Allows a user to configure site-wide default Galaxy instances.' )
    )
  );
}

/**
 * Implements hook_menu()
 *
 * Specifies menu items and URLs used by this module.
 *
 * @ingroup tripal_galaxy
 */
function tripal_galaxy_menu() {
  $items = array ();

  // EXPLANATION: all extension modules should have an administrative menu item
  // with the path set to 'admin/tripal/extension/[module name]'.
  $items['admin/tripal/extension/galaxy'] = array (
    'title' => 'Manage Galaxy Instances',
    'description' => 'Integrate workflows from a remote Galaxy instance with this Tripal site',
    'page callback' => 'tripal_galaxy_admin_home',
    'access arguments' => array('administer galaxy'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'includes/tripal_galaxy.admin.inc',
    'file path' => drupal_get_path ('module', 'tripal_galaxy')
  );

  // Edit Galaxy
  $items['admin/tripal/extension/galaxy/edit/%'] = array (
    'description' => 'Edit a galaxy instance',
    'page callback' => 'drupal_get_form',
    'page arguments' => array ('tripal_galaxy_admin_configuration_form', 5),
    'access arguments' => array ('administer galaxy'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/tripal_galaxy.admin.inc',
    'file path' => drupal_get_path ( 'module', 'tripal_galaxy' )
  );

  // Add Galaxy
  $items['admin/tripal/extension/galaxy/add'] = array (
    'description' => 'add a galaxy instance',
    'title' => 'Add Galaxy Instance',
    'page callback' => 'drupal_get_form',
    'page arguments' => array (
      'tripal_galaxy_admin_configuration_form'
    ),
    'access arguments' => array (
      'administer galaxy'
    ),
    'type' => MENU_LOCAL_ACTION,
    'file' => 'includes/tripal_galaxy.admin.inc',
    'file path' => drupal_get_path ( 'module', 'tripal_galaxy' )
  );

  // Available Workflows
  $items['admin/tripal/extension/galaxy/available_wf'] = array(
    'title' => 'Workflows',
    'description' => 'Lists the available workflows for the user',
    'page callback' => 'drupal_get_form',
    'page arguments' => array(
      'tripal_galaxy_admin_available_wf_form',
    ),
    'access arguments' => array (
      'administer galaxy'
    ),
    'type' => MENU_LOCAL_TASK,
    'file' => 'includes/tripal_galaxy.admin_wf_form.inc',
    'file path' => drupal_get_path('module', 'tripal_galaxy')
  );

  // Add Workflows
  $items['admin/tripal/extension/galaxy/available_wf/add_wf'] = array(
    'title' => 'Add Workflows',
    'description' => 'Add workflows to the site given the remote galaxy instance',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tripal_galaxy_admin_add_wf_form'),
    'access arguments' => array('administer galaxy'),
    'type' => MENU_LOCAL_ACTION,
    'file' => 'includes/tripal_galaxy.admin_wf_form_add.inc',
    'file path' => drupal_get_path('module', 'tripal_galaxy' )
  );

  // Remove Workflows
  $items['admin/tripal/extension/galaxy/available_wf/remove/%'] = array (
    'description' => 'Remove a Workflow from site',
    'page callback' => 'tripal_galaxy_admin_remove_wf',
    'page arguments' => array(6),
    'access arguments' => array('administer galaxy'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/tripal_galaxy.admin.inc',
    'file path' => drupal_get_path ( 'module', 'tripal_galaxy' )
  );

  // Usage
  $items['admin/tripal/extension/galaxy/usage'] = array (
    'title' => 'Usage',
    'description' => 'Explore Galaxy usage details.',
    'page callback' => 'drupal_get_form',
    'page arguments' => 'tripal_galaxy_admin_usage_form',
    'access arguments' => array (
      'administer galaxy'
    ),
    'type' => MENU_LOCAL_TASK,
    'file' => 'includes/tripal_galaxy.admin.inc',
    'file path' => drupal_get_path ( 'module', 'tripal_galaxy' )
  );

  // Submitted
  $items['admin/tripal/extension/galaxy/submitted'] = array (
    'title' => 'Submitted',
    'description' => 'View Submitted workflows',
    // Are we sure about this?
    'page callback' => 'tripal_galaxy_admin_submitted_list',
    'access arguments' => array (
      'administer galaxy'
    ),
    'type' => MENU_LOCAL_TASK,
    'file' => 'includes/tripal_galaxy.admin.inc',
    'file path' => drupal_get_path ( 'module', 'tripal_galaxy' )
  );

  // Workflow
  $items['workflows'] = array (
    'title' => 'Available Workflows',
    'description' => 'A list of available analytical workflows for this site',
    // Are we sure about this?
    'page callback' => 'test_webforms',
    'access arguments' => array (
      'administer galaxy'
    ),
    'type' => MENU_LOCAL_TASK,
    'file' => 'includes/tripal_galaxy.user.inc',
    'file path' => drupal_get_path ( 'module', 'tripal_galaxy' )
  );

  // Galaxy
  $items['user/galaxy'] = array (
    'title' => 'Galaxy',
    'description' => 'Configure Galaxy Server',
    // Are we sure about this?
    'page callback' => 'drupal_get_form',
    'page arguments' => 'tripal_galaxy_user_configuration_form',
    'access arguments' => array (
      'use galaxy'
    ),
    'type' => MENU_LOCAL_TASK,
    'file' => 'includes/tripal_galaxy.user.inc',
    'file path' => drupal_get_path ( 'module', 'tripal_galaxy' )
  );

  return $items;
}

/**
 * Implements hook_views_api()
 *
 * This hook tells drupal that there is views support for
 * for this module which then automatically includes the tripal_db.views.inc
 * where all the views integration code is found.
 *
 * @ingroup tripal_galaxy
 */
function tripal_galaxy_views_api() {
  return array (
    'api' => 3.0
  );
}

/**
 *  We need to let drupal know about our theme functions and their arguments.
 *  We create theme functions to allow users of the module to customize the
 *  look and feel of the output generated in this module
 *
 * @ingroup tripal_galaxy
 */
function tripal_galaxy_theme($existing, $type, $theme, $path) {
  $items = array (
    'tripal_galaxy_admin_add_wf_form_rows' => array (
      'render element' => 'form'
    ),

    'tripal_galaxy_admin_available_wf_form_rows' => array(
      'render element' => 'form'
    )

  );
  return $items;
}

/**
 * Implements hook_help()
 *
 * Adds a help $formpage to the module list
 */
function tripal_galaxy_help($path, $arg) {

  // EXPLANATION: in the tripal_galaxy_menu() function above we created
  // a menu item for the help documentation. The menu item specified
  // a function that should be called when the menu item is clicked. This
  // is that function. But, rather than place HTML code in this function
  // we want to have our help documentation in a template galaxy. We
  // specified in the tripal_galaxy.theme() function that we have a template
  // galaxy so now we want to use get the contents of that template galaxy and
  // return it.
  if ($path == 'admin/help#tripal_galaxy') {
    return theme ( 'tripal_galaxy_help', array () );
  }
}